import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { ClerkProvider, SignUp, SignIn, SignedIn, SignedOut } from "@clerk/clerk-react";   // Clerk authorization imports

import Layout from '@/components/Layout'
import SignInPage from '@/components/SignInPage';

const inter = Inter({ subsets: ['latin'] })

// Load any necessary ENV variables
const clerkPubKey = process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY;

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <ClerkProvider publishableKey={clerkPubKey}>
          <SignedIn>
            <Layout/>
          </SignedIn>
          <SignedOut>
            <SignInPage/>
          </SignedOut>
        </ClerkProvider>
      </main>

    </>
  )
}
